### PR TITLE
46 - Volume design update

### PR DESCRIPTION
**Pull request by bent0b0x**
**Issue**
[paratii-mediaplayer#46](https://github.com/Paratii-Video/paratii-mediaplayer/issues/46)

**Work Done**
Hide volume bar until user interacts w/ it. Then dismiss it after a timeout.

**Demo**

volumewin

@pedrocasa let me know if this is the correct general direction. This is still a WIP on my side so please let me know what changes you'd like to see!

### CODE REVIEW

**Comment by bent0b0x** [comment]
@pedrocasa I've started to implement this as you can see in the gif above. However, I don't think having the volume bar grow on hover when the button is on the right side of the controls is a good UX, because you hover over the button and it moves.

Solutions:
- move the volume to the left side of the player
- have the volume bar grow vertically on top of the volume button instead of horizontally.

Thoughts?

**Comment by bent0b0x** [comment]
This is essentially good to go. I just need one new icon (new volume icon to match size of new mute icon) and then this is ready.

**Comment by pedrocasa** [comment]
Ben, just to know. Is this related to last design that Ive made on issue ?https://github.com/Paratii-Video/paratii-mediaplayer/issues/46#issuecomment-374067463

**Comment by pedrocasa** [comment]
By this on last comment I meant this "pedrocasa I've started to implement this as you can see in the gif above. However, I don't think having the volume bar grow on hover when the button is on the right side of the controls is a good UX, because you hover over the button and it moves.

Solutions:

move the volume to the left side of the playerhave the volume bar grow vertically on top of the volume button instead of horizontally.

Thoughts?

"

**Comment by bent0b0x** [comment]
@pedrocasa yes, I wrote that comment before seeing your latest design. I've moved the bar to the left 👍.

I've got a few subtle things to improve to match the design, when it's done I'll reupload

**Comment by pedrocasa** [comment]
Great. I don't know what changes it'll have in the next update. But we may consider resize the volume bar width so it can looks more as the desigb specs ( Im sorry if u are already planning to do/doing it 🙈)

**Comment by bent0b0x** [comment]
@pedrocasa lmk what you think! Adjusted the size of the bar and added gray coloring for the part of the volume bar that hasn't been selected. Also, I added a border radius to the bar. Happy to update further if you see other things to improve.

One thing I have not done here is add the transparent background circle to the volume indicator. I am tracking that issue [here](https://github.com/Paratii-Video/paratii-portal/issues/378) because the same thing will need to be done for the player progress bar indicator.

volumesizewin

**Comment by pedrocasa** [comment]
Amazing! Still want to see how it behaves in other screen sizes but from Ive seen from this gif I think we are good to go

**Comment by bent0b0x** [comment]
Cool 👍 . In all likelihood I (or Jelle) will merge this and then I will tackle the all of the player control sizes next in the separate issue that I have created.

**Pull request merged**
