### PR TITLE
configure bundlesize

### PR DESCRIPTION
**Pull request by jellegerbrandy**
this should show info on bundlesize inc circleci #716

### CODE REVIEW

**Comment by bent0b0x** [comment]
Looks awesome, just not sure if it is working yet? Don't see anything on circle or this PR

**Comment by jellegerbrandy** [comment]
yeah, neither do I, there must be some config step that I'm missing...

**Comment by jellegerbrandy** [comment]
Damn, bundlesize reports the wrong values: https://bundlesize-store.now.sh/build?info=%7B%22files%22%3A%5B%7B%22maxSize%22%3A1048576%2C%22path%22%3A%22.%2Fbuild%2F1.bundle.js%22%2C%22size%22%3A2830862%2C%22compression%22%3A%22gzip%22%7D%2C%7B%22maxSize%22%3A1048576%2C%22path%22%3A%22.%2Fbuild%2Fbundle.js%22%2C%22size%22%3A4250775%2C%22compression%22%3A%22gzip%22%7D%2C%7B%22maxSize%22%3A1048576%2C%22path%22%3A%22.%2Fbuild%2Fipfs.bundle.js%22%2C%22size%22%3A3239093%2C%22compression%22%3A%22gzip%22%7D%5D%2C%22repo%22%3A%22Paratii-Video%2Fparatii-portal%22%2C%22branch%22%3A%22feat%2F716-bundlesize%22%2C%22commit_message%22%3A%22%22%2C%22sha%22%3A%228466025b33d6093279b24f9f28bdfdf224546c11%22%7D

**Comment by jellegerbrandy** [comment]
It works now, but we need to somehow get bundlesize to report the correct values otherwise it is pretty useless... according to the dcos, it is supposed to report the gzipped size, which it is certainly not doing. @bent0b0x , if i don't get to this today can you have a look to see if it is something obvious I am overlooking?

**Comment by jellegerbrandy** [comment]
The thing is that bundlesize is reporting the correct sized in the console, but the reported sized in the link uner "all checks have passed" is wrong :-/

**Pull request closed without merging**
