### PR TITLE
81 - show avatar

### PR DESCRIPTION
**Pull request by eliawk**
add react-blockies, the avatar is now based on the eth address.

`react-blockies` is a simple port of [](https://github.com/alexvandesande/blockies to a react component.)

### CODE REVIEW

**Comment by eliawk** [comment]
@bent0b0x i'm fighting with `stylelint`. it auto change a file and then it tells me there are errors which it has created!

**Comment by bent0b0x** [comment]
@eliawk I don't think `stylelint` changes any files. Are you sure it is not `prettier-standard` doing the changes?

**Comment by bent0b0x** [comment]
If [this rule](https://stylelint.io/user-guide/rules/declaration-colon-newline-after/) conflicts w/ prettier I would disable it.

**Comment by jellegerbrandy** [comment]
fixed the linter problem with #90,

**Pull request merged**
