### PR TITLE
544 - autoplay UX fix

### PR DESCRIPTION
**Pull request by bent0b0x**
**Issue**
#544 

**Work Done**
- allow showing of start scree (big play button) in portal player
- when autoplay fails (for whatever reason, but most likely because safari/chrome have blocked it for various reason), keep the start screen visible so that user knows to manually play video

**Demo**

autoplaywin

☝️ previously, the start screen/play button would disappear after autoplay is blocked

cc @pedrocasa

### CODE REVIEW

**Comment by jrgarou** [comment]
Nice.
I think the _play button_ should be visible/enable when there's a video to play. If the _play button_ doesn't trigger any action we should hide it until so.

**Comment by bent0b0x** [comment]
@jrgarou do you mean the big play button or the play button on the controls bar?

Can you elaborate a bit more on a particular situation when you think we should hide it when we are not currently hiding it?

**Comment by jrgarou** [comment]
@bent0b0x if there's no situation when the big play button and controls are visible and the video is not ready I think is fine.

**Comment by jellegerbrandy** [comment]
can you fix the conflict? thks

**Comment by bent0b0x** [comment]
On it

**Comment by bent0b0x** [comment]
@jrgarou I _think_ we should be fine here. If the video hasn't loaded yet clicking play should trigger clappr to play once it has buffered enough. So the play button should trigger an action always even if we aren't ready to play immediately.

I will add a condition to not show the button until we have loaded a clappr player, I think that will cover our bases

**Comment by jellegerbrandy** [comment]
did this now go in conflict with your other PR I just merged? :-)

**Comment by jrgarou** [comment]
@bent0b0x we can define this here:
https://github.com/Paratii-Video/paratii-portal/blob/ec88c867bb57ebae8c5420cc738f718dd698dcaf/src/scripts/components/Play.js#L749-L753

**Comment by bent0b0x** [comment]
@jellegerbrandy fixed!

**Pull request merged**
