### PR TITLE
GZIP!! and minifying all but IPFS

### PR DESCRIPTION
**Pull request by ya7ya**
this is part of the effort to properly uglify the production build. 
I managed to split IPFS in a separate bundle here https://github.com/Paratii-Video/paratii-lib/pull/162
but this still breaks in `production` mode. i'm debugging the issue 😞 

ref https://github.com/Paratii-Video/paratii-portal/issues/194#issuecomment-372827913

### CODE REVIEW

**Comment by bent0b0x** [comment]
@ya7ya if we follow the dependency philosophy that our libraries should not come w/ any dependencies and instead rely on applications to provide them, then I think our problem becomes easier. Make `ipfs` a `peerDependency` and then tell `webpack` in `paratii-lib` to not bundle it and instead rely on it to be provided later. See [example in paratii-mediaplayer](https://github.com/Paratii-Video/paratii-mediaplayer/blob/master/webpack.config.js#L87-L92). `paratii-mediaplayer` does not come w/ any dependencies bundled. 

Then, in the portal we can easily update the `webpack` config to treat `ipfs-js` differently.

So moving to `peerDependencies` helps in this case but I think it is also a good idea because it prevents double dependency bundling.

**Comment by jellegerbrandy** [comment]
Ok, there is one part i do not understand yet about peerdependencies. No,
two :-)

1. As far as I can see, we are not using a "bundled" version of paratii-lib
for the portal bunble (
https://github.com/Paratii-Video/paratii-portal/blob/dev/src/scripts/utils/ParatiiLib.js#L3).
So it is unclear to me why peerdepdenceis would make a difference here.

2. More of a general question: we depend on 10s of packages and 100s of
modules, all not using peer dependencies. It is unclear to me why
paratii-lib in particular is problematic here and needs to use peer
dependencies..

**Comment by bent0b0x** [comment]
1. If we are not using the bundled version, then all of the dependencies are already being treating as peer dependencies. Meaning that the portal has to install and provide them all. If this is the recommended way to use `paratii-lib`, then I think `paratii-lib` should mark all of the deps as peer deps so it is clear that any use of the lib needs to install these things or else the library will not work.

So, if `paratii-portal` is already the one providing `ipfs-js`, @ya7ya why can't we just update portal's webpack.config.js to not mangle or uglify `ipfs-js`? Or mangle it specially?

2. I could be wrong, but I think it is just not standard practice b/c it makes libraries more difficult to install and use when you use peer dependencies. But in the end it definitely keeps your bundle size smaller and prevents duplicate dependencies if the app is the only one providing dependencies.

**Comment by ya7ya** [comment]
I just realized that the express server here didn't have the `compression` middleware!!! , this significantly reduces the size of the files to under 1mb 💨

**Pull request merged**
