### PR TITLE
[WIP] - 373 - reduce controls height

### PR DESCRIPTION
**Pull request by bent0b0x**
**Issue**
#373 

**Work Done**
Reduce player controls height

**Demo**

controlsheightwin

☝️ @pedrocasa @felipegaucho what do you think?

### CODE REVIEW

**Comment by pedrocasa** [comment]
Almost there,  just need little tight. Was the previous one the same value as the adobe specs?

**Comment by felipegaucho** [comment]
For comparison (note our icons are should also be probably ~70% of their current size), and the bar, depending on @pedrocasa specs, thinner too (maybe 80%):

controlsheightwin 
screen shot 2018-03-20 at 12 01 55 am
screen shot 2018-03-20 at 12 02 18 am

**Comment by bent0b0x** [comment]
@pedrocasa no the previous value came from...I'm not sure where! My head I guess haha.

I can look into this more in depth. One thing the controls do not have right now are media query breakpoints for different screen sizes. I'll add those in this PR, and it can control the height of the bar and icon sizes if needed 👍

**Comment by bent0b0x** [comment]
Also @pedrocasa should the controls bar have some transparency?

**Comment by pedrocasa** [comment]
@felipegaucho on the issue#371  last comments of ben it's already smaller.
Am I right Ben? 
( thalking about the elements inside the video bar)

**Comment by pedrocasa** [comment]
@bent0box the grey part ( not playing yet) does. 90%

**Comment by bent0b0x** [comment]
@pedrocasa the volume button specifically is smaller in that issue, but I have not expanded that to other controls yet

**Comment by pedrocasa** [comment]
Should I point to these dimension corrections or do you already intend to change them one at a time? (according to the specs)

**Comment by bent0b0x** [comment]
I plan on fixing them all together starting tomorrow. I am pretty sure I have all of the numbers I need in the adobe specs, but I will let you know if I run into any questions!

**Comment by pedrocasa** [comment]
Great!

**Comment by pedrocasa** [comment]
@bent0b0x I don't when u did the last PR but the current version of the video bar still a little thick

**Pull request merged**
