### PR TITLE
185 - indicate which video is selected in uploader

### PR DESCRIPTION
**Pull request by bent0b0x**
**Issue**
#187 

Indicate in the Uploader UI which video is selected.

selected

### CODE REVIEW

**Comment by pedrocasa** [comment]
Hi Ben, 
this light grey rectangle was designed to indicate which video you are selecting

capture

**Comment by bent0b0x** [comment]
Got it, @pedrocasa. Right now, we are using that light gray for every other video in the list to make the list look prettier. Are you okay with just scrapping that and giving all videos here (except selected one) same background?

**Comment by eliawk** [comment]
@ben this was the original @pedrocasa idea, using the light gray to display the selected video, but this was misunderstood and has became the `:odd` list item color

**Comment by bent0b0x** [comment]
@eliawk @pedrocasa changed the color (see screenshot above)

**Pull request merged**
